### ISSUE TITLE
ibis beginner error

### ISSUE THREAD

**Issue by karens99** [williamslab/ibis#1]
Hi, I am trying to run IBIS on a set of plink binary files, with no additional options, but am getting no output, and a comment that says "Illegal instruction".  The plink binary files work fine in plink and king, so I wonder if I am doing something else wrong.  Please see my code and log below; any help is appreciated!

Here is my command: 

ibis -b freeze1.chr10.allfam.filtered

Here is the log:

IBIS Segment Caller!  v1.19.2    (Released March 9, 2020)
Viewing arguments...
-b - Running with input files: freeze1.chr10.allfam.filtered.bed, freeze1.chr10.allfam.filtered.bim, freeze1.chr10.allfam.filtered.fam
No prefix given. Defaulting filenames to prefix "ibis"
Parsing SNP file... WARNING: Setting genetic position from physical
done.
Parsing individual file... done.
Parsing genotype file... initiated, to complete later.
Chromosome map shorter than 6 units of genetic distance.
 Morgan input detected - Converting to centimorgans. (Prevent this by running with -noConvert argument)
Defining Windows... done.
Organizing genotype data for analysis... done.
Beginning segment detection with 1 thread(s)...Illegal instruction (core dumped)

**Comment by DanielSeidman** [comment]
Hello!

It looks like you are using v1.19.2.
As of the most recent release, we changed the behaviors of ibis in the
event that you do not include a genetic map in the bim file, so that it
replaces the 0s for the genetic map with a mapping of 1Mb to 1cM. You may
be experiencing problems due to IBIS not properly handling the lack of map
in the input.
Did you not insert a map into the bim file you were using?
If you did not, it may be worth trying v1.19.3 in the release we sent out
yesterday, or try inserting a map into the bim file yourself.

**Comment by DanielSeidman** [comment]
After discussing this, we realize that it is also possible that your
computer may not have the popcount functionality. We didn't have access to
a processor without the popcount function to confirm whether or not this
could be an issue for certain machines. Is it possible for you to compile
IBIS yourself? That should theoretically resolve the issue if you do
(though you may also still want v1.19.3 for a separate reason).
If not, let us know, and we could look into making an executable that will
work for you.

**Comment by karens99** [comment]
Thanks for your responses.  We did update to v1.19.3 based on your recommendation, but we are still having the same issue.  I am not inserting a map into the bim file yet, as I am just getting started with IBIS, and wanted to see how it would work without it.  I will try adding the map, and see how it goes.  In addition, I will discuss your 2nd comment with our IT manager, and let you know his response.

**Comment by williamslab** [comment]
I'm going to close this, but please let us know if we can help further.
