### ISSUE TITLE
Perform analysis in just one sample in your dataset

### ISSUE THREAD

**Issue by KnowToLearn** [williamslab/ibis#10]
Hello,
I am starting some analyses with a huge dataset using IBIS. I was wondering if it possible to carry out the calculation of .seg and .coef for just one sample in my dataset against the resto of the dataset, instead of running the analyses for all the samples vs all the samples together. This would be very helpful if I am interested in just one sample, and avoid post-processing filters in the output tables every time I perform a different analysis.

I really appreciate your help.

**Comment by williamslab** [comment]
If you can order the PLINK files so that the sample you want to compare against the others is first, you can use `-setIndexStart 0 -setIndexEnd 0`. That compares the first sample, index 0, against all other samples in the dataset.

**Comment by KnowToLearn** [comment]
Thank you so much for your quick help. If I set the flag -setIndexEnd I obtain the error "Cannot select starting ending index less than or equal to 0.". I used -setIndexEnd 1 and it worked.
