### ISSUE TITLE
Problems with install  [Makefile:51: ibis] Error 1

### ISSUE THREAD

**Issue by nalbright** [williamslab/ibis#11]
I keep having an error message pop up when trying to run make. 
First I cloned the repo as per readme
`git clone --recurse-submodules https://github.com/williamslab/ibis.git`

Then I cd'ed into `ibis/` and ran `make`  Below is the following error message. Are there required dependencies/packages that I could be missing? 

Thanks in advance for your help
-Nicolette 

Onscreen message: 

g++ -MMD -std=c++2a -I. -Wall  -fopenmp -mpopcnt -O3 -o IBIS.o -c IBIS.cc
g++ -MMD -std=c++2a -I. -Wall  -fopenmp -mpopcnt -O3 -o genetio/personio.o -c genetio/personio.cc
g++ -MMD -std=c++2a -I. -Wall  -fopenmp -mpopcnt -O3 -o genetio/marker.o -c genetio/marker.cc
g++ -MMD -std=c++2a -I. -Wall  -fopenmp -mpopcnt -O3 -o genetio/superperson.o -c genetio/superperson.cc
g++ -MMD -std=c++2a -I. -Wall  -fopenmp -mpopcnt -O3 -o genetio/personloopdata.o -c genetio/personloopdata.cc
g++ -MMD -std=c++2a -I. -Wall  -fopenmp -mpopcnt -O3 -o genetio/personbulk.o -c genetio/personbulk.cc
g++ -MMD -std=c++2a -I. -Wall  -fopenmp -mpopcnt -O3 -o genetio/nuclearfamily.o -c genetio/nuclearfamily.cc
g++ -MMD -std=c++2a -I. -Wall  -fopenmp -mpopcnt -O3 -o genetio/util.o -c genetio/util.cc
g++ -o ibis IBIS.o genetio/personio.o genetio/marker.o genetio/superperson.o genetio/personloopdata.o genetio/personbulk.o genetio/nuclearfamily.o genetio/util.o  -I. -Wall  -fopenmp -mpopcnt -O3 -lz
<anaconda_path>/bin/../lib/gcc/x86_64-conda-linux-gnu/11.2.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lz: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [Makefile:51: ibis] Error 1

**Comment by DanielSeidman** [comment]
The -lz issue implies it is unable to find a libz library.
I think it's libz.a specifically?

**Comment by williamslab** [comment]
Can you confirm that installing libz resolves this?

**Comment by williamslab** [comment]
I'll close this for now, but please let us know if we can help.
