### ISSUE TITLE
Error with install

### ISSUE THREAD

**Issue by oleraj** [williamslab/ibis#12]
Hi,

I'm getting this error message when running make:
```
make
	g++ -MMD -std=c++2a -I. -Wall  -fopenmp -mpopcnt -O3 -o IBIS.o -c IBIS.cc
	g++: error: unrecognized command line option ‘-std=c++2a’
	make: *** [Makefile:72: IBIS.o] Error 1
```

I'm using GCC v. 5.4.0.  I also tried with 4.8.5, which gave the same error message.  Any recommendations for how to get this to work with this version of GCC?  Or is there a different recommended version of GCC to use?

Thanks,

Andrew

**Comment by DanielSeidman** [comment]
There was another individual with a similar concern recently.
They ended up asking and received an answer here:
https://www.biostars.org/p/9562548/#9562596
Hope this is useful.

**Comment by oleraj** [comment]
Thanks @DanielSeidman. Yes, it looks like my GCC version is too old.

After this, I tried GCC v.8.3.0 and was able to get past this error message but then got an error about the "bit" header.  In the end, I was able to successfully compile the package using GCC 10.3.0.  Hopefully that is helpful to others.

**Comment by mufernando** [comment]
Hi @williamslab,

I ran into this same issue, but was able to solve it by using GCC 9.3. I tried GCC 8.3 and it failed as well.

It might be worth adding this bit of info to the installation bit of the readme.

Thanks for the awesome software!

Murillo
