### ISSUE TITLE
Issue with low-density dataset: Segments capped at 64 SNPs

### ISSUE THREAD

**Issue by magnusdv** [williamslab/ibis#13]
Hi,

I applied IBIS to a dataset containing ~4000 SNPs from pairs of siblings, hoping to identify their IBD segments and recombination crossover points. However (by comparing with other methods) I find the segments reported by IBIS are frequently too short, and suspiciously often contain exactly 64 SNPs. This persist even when without any filtering, i.e. `-mt 0 -mL 0`.

From reading the paper I understand that the algorithm uses non-overlapping windows of hardcoded size 64 markers. So I guess the explanation lies there. 

Is there a recommended lower limit for SNP density? I don't see any mention of this anywhere, so I kind of hoped that the implementation included a workaround for lower densities. If not, you might consider having IBIS issue a warning in such cases.

Or is there a way I can trick IBIS to improve its accuracy with my ~4000 SNPs?

Thanks for your time!
Magnus

**Comment by williamslab** [comment]
Hi Magnus,

You're right about the windows being exactly 64 SNPs. With only 4000 SNPs, I would think that IBIS's accuracy wouldn't be great: it's difficult to call unphased IBD reliably in general. I would suggest having as many SNPs as possible :) but I'd say SNP densities in humans of 300,000+ SNPs or so may make IBIS work reasonably, especially in siblings.

We're not aware of any bugs in IBIS, but if there are segments that other tools are finding that IBIS is not, we could debug that. The trick is finding a segment that would have a neighboring window of 64 SNPs called as IBD that IBIS is not calling. If you have such a case, that may be a bug.

Hope that helps! I'd say for this SNP density, IBIS is perhaps not the best IBD caller.

**Comment by magnusdv** [comment]
Many thanks, that is clarifying.
I'll come back to IBIS when I have a richer dataset. :)
