### ISSUE TITLE
Problemi IBS installation

### ISSUE THREAD

**Issue by Luciagenetic** [williamslab/ibis#7]
hi i can't get ibis running maybe i have a problem with the installation.
I am to insert the map in cm in the bim file but the following steps do not work

**Comment by DanielSeidman** [comment]
Hello!
Can you describe what happens with the bim file in more detail?
Also can you describe the format of the map file you are using?
If the genetic positions in the bim file are still 0 after running the insertion script, it may mean the map you are using is in the wrong format, which is the most common problem I see people have with this step. There are multiple different formats for storing genetic map data and the insertion script doesn't read all of them correctly.

**Comment by Luciagenetic** [comment]
pedigree in graph. thanks

Ottenere Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Luciagenetic** [comment]
I have changed the default parameters for both IBD1 and IBD2 as ouput I have done both coef in coef seg and the file for the ROH in this I will have to decrease the markerconsider threshold. the degree of kinship is likely. is there any software that takes these results to build a pedigree?
thanks to the availability

Ottenere Outlook per Android<https://aka.ms/AAb9ysg>
________________________________
