### ISSUE TITLE
cant dectect IBD  in a magic population

### ISSUE THREAD

**Issue by lgbTime** [williamslab/ibis#8]
I has a unphased vcf INFO from a magic population of lettuce, there are 390 individual, among them 17 are the parent, when I use the IBIS to detect the IBD, with command  "./ibis chr1.bed chr1.bim chr1.fam -min_l 7 -mt 500 -er .004 -f test_IBIS_Out", I found that there are no IBD dected between parent sample and generation sample, is that the IBIS method cant be used in magic population or cant be applied  in plants fields ?

**Comment by williamslab** [comment]
Going to close this, but please let us know if you still have concerns.
